### ISSUE TITLE
Unable to handle package.xml format version '3'

### ISSUE THREAD

**Issue by stevenczwu** [niosus/catkin_tools_fetch#19]
Hey there. I am trying to run it on a virtual machine, and I got error as this:
**Unable to handle package.xml format version '3'**

I tried with **sudo apt-get update** && **sudo apt-get install --only-upgrade python-catkin-pkg**, but it is still not working... do you have any idea? Thanks!

**Comment by niosus** [comment]
Hey @stevenczwu 
I guess the fix should be as simple as just allowing for numbers higher than 2 in the version field. I will try to look into this soon.

**Comment by niosus** [comment]
Looking deeper into this, it seems this error has nothing to do with `fetch` but is an error from somewhere else. I've just modified the tests to check if it works with `package.xml` format version 3 and it does. So I will close this issue as it is related to some other tool. Feel free to reopen if I am actually wrong.

**Comment by niosus** [comment]
Just as a proof: https://github.com/PRBonn/catkin_tools_fetch/pull/20
